{
 "title": "Prometheus Telegraf Docker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent"
    }
   ]
  },
  {
   "title": "Docker Memory Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_memory_total" }
   ]
  },
  {
   "title": "Mem Usage COMMENT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage{com_docker_compose_service=\"comment\",container_image=\"max2l/comment\"}"
    }
   ]
  },
  {
   "title": "Cpu Usage COMMENT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{com_docker_compose_service=\"comment\",container_image=\"max2l/comment\"}"
    }
   ]
  },
  {
   "title": "Mem Usage POST",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage{com_docker_compose_service=\"post\",container_image=\"max2l/post\"}"
    }
   ]
  },
  {
   "title": "Cpu Usage POST",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{com_docker_compose_service=\"post\",container_image=\"max2l/post\"}"
    }
   ]
  },
  {
   "title": "Mem Usage UI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage{com_docker_compose_service=\"ui\",container_image=\"max2l/ui\"}"
    }
   ]
  },
  {
   "title": "Cpu Usage UI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{com_docker_compose_service=\"ui\",container_image=\"max2l/ui\"}"
    }
   ]
  }
 ]
}